#
# QUERIES
#

extend type Query {
  """
  Select an Ability by its snake_case name, e.g. 'intimidate', 'rks_system'.
  """
  abilityByName(
    generation: Int = 8
    generations: [Int]
    name: String!
  ): [Ability!]! 
  
  """
  Select Abilities by their snake_case name, e.g. 'intimidate', 'rks_system'.
  """
  abilitiesByName(
    generation: Int = 8
    generations: [Int]
    names: [String!]!
  ): [Ability!]! 

  """
  Select an Ability by its psID, e.g. 'intimidate', 'rkssystem'.
  """
  abilityByPSID(
    generation: Int = 8
    generations: [Int]
    psID: String!
  ): [Ability!]! 
  
  """
  Select Abilities by their psID, e.g. 'intimidate', 'rkssystem'.
  """
  abilitiesByPSIDs(
    generation: Int = 8
    generations: [Int]
    psIDs: [String!]!
  ): [Ability!]! 
  
  """
  Select Abilities with filtering and pagination.
  """
  abilities(
    generation: Int = 8
    pagination: AbilityPaginationInput
    filter: AbilityFilter
  ): AbilityConnection!
}

#
# TOP-LEVEL CONNECTION
#

type AbilityConnection implements Connection {
  id: String!
  count: Int!
  
  edges: [AbilityEdge!]!
}

type AbilityEdge implements Edge {
  node: Ability!
}

#
# NODES AND HELPER TYPES
#


"""
An Ability which a Pokemon can possess.
"""
type Ability implements Node {
  id: ID!

  """
  E.g. 'harsh_sunlight' activates 'chlorophyll'.
  """
  activatedByFieldState(filter: FieldStateFilter, pagination: FieldStatePaginationInput): AbilityActivatedByFieldStateConnection

  """
  E.g. 'sound' activates 'liquid_voice'.
  """
  activatedByUsageMethod(filter: UsageMethodFilter, pagination: UsageMethodPaginationInput): AbilityActivatedByUsageMethodConnection

  """
  E.g. 'blaze' boosts 'fire'.
  """ 
  boostsType(filter: TypeFilter, pagination: TypePaginationInput): AbilityBoostsTypeConnection

  """
  E.g. 'liquid_voice' boosts 'sound'.
  """
  boostsUsageMethod(filter: UsageMethodFilter, pagination: UsageMethodPaginationInput): AbilityBoostsUsageMethodConnection

  """
  E.g. 'poison_point' causes 'poison'.
  """
  causesStatus(filter: StatusFilter, pagination: StatusPaginationInput): AbilityCausesStatusConnection

  """
  E.g. 'electric_surge' creates 'electric_terrain'.
  """
  createsFieldState(filter: FieldStateFilter, pagination: FieldStatePaginationInput): AbilityCreatesFieldStateConnection

  """
  The Descriptions for the Ability across the different VersionGroups.
  """
  descriptions(filter: DescriptionFilter, pagination: DescriptionPaginationInput): AbilityDescriptionConnection

  """
  E.g. 'forecast' has the Effect 'changes_pokemon_type'. 
  """
  effects(filter: EffectFilter, pagination: EffectPaginationInput): AbilityEffectConnection

  """
  The name of the Ability in Title Case, with appropriate punctuation and capitalization. 

  For example:
    'RKS System' instead of 'Rks System'
    'Power of Alchemy' instead of 'Power Of Alchemy'
  """
  formattedName: String!

  """
  The Generation of this Ability.
  """ 
  generation(filter: GenerationFilter, pagination: GenerationPaginationInput): AbilityGenerationConnection

  """
  E.g. 'levitate' ignores 'sticky_web', 'infiltrator' ignores 'reflect'.
  """
  ignoresFieldState(filter: FieldStateFilter, pagination: FieldStatePaginationInput): AbilityIgnoresFieldStateConnection

  """
  The Generation in which the Ability was introduced.
  """ 
  introduced(filter: GenerationFilter, pagination: GenerationPaginationInput): AbilityIntroductionConnection

  """
  E.g. 'intimidate' modifies 'attack'.
  """
  modifiesStat(filter: StatFilter, pagination: StatPaginationInput): AbilityModifiesStatConnection

  """
  The name of the Ability in snake_case.
  """
  name: String!

  """
  Pokemon which can possess this Ability.
  """
  pokemon(filter: PokemonFilter, pagination: PokemonPaginationInput): AbilityPokemonConnection
  
  """
  ID of the Ability in Pokemon Showdown's code for use with, e.g. the package 'pkmn/sets' for Pokemon movesets.
  """
  psID: String!

  """
  E.g. 'cloud_nine' prevents 'aurora_veil' from being set up, even in the presence of 'hail'. This is because 'cloud_nine' suppresses the effects of 'hail'. 'cloud_nine' does not remove or suppress 'aurora_veil' that is already set-up. 
  """
  preventsFieldState(filter: FieldStateFilter, pagination: FieldStatePaginationInput): AbilityPreventsFieldStateConnection

  """
  E.g. 'damp' prevents 'explosive'.
  """
  preventsUsageMethod(filter: UsageMethodFilter, pagination: UsageMethodPaginationInput): AbilityPreventsUsageMethodConnection

  """
  E.g. 'drizzle' removes other weather effects.
  """
  removesFieldState(filter: FieldStateFilter, pagination: FieldStatePaginationInput): AbilityRemovesFieldStateConnection

  """
  E.g. 'water_absorb' resists 'water', with a multiplier of 0. Also applies to Abilities which give weaknesses to types (e.g. we say 'dry_skin' resists 'fire', with a multiplier of 1.25).
  """
  resistsType(filter: TypeFilter, pagination: TypePaginationInput): AbilityResistsTypeConnection

  """
  E.g. 'soundproof' resists 'sound'.
  """
  resistsUsageMethod(filter: UsageMethodFilter, pagination: UsageMethodPaginationInput): AbilityResistsUsageMethodConnection

  """
  E.g. 'flower_veil' resists 'sleep'. 
  """
  resistsStatus(filter: StatusFilter, pagination: StatusPaginationInput): AbilityResistsStatusConnection

  """
  E.g. 'cloud_nine' suppresses weather effects, but does not remove them (if the Pokemon is switched out, the effects return).
  """
  suppressesFieldState(filter: FieldStateFilter, pagination: FieldStatePaginationInput): AbilitySuppressesFieldStateConnection
}

#
# CONNECTIONS AND EDGES
#

# DESCRIPTION 

type AbilityDescriptionConnection implements Connection {
  id: String!
  count: Int!
  
  edges: [AbilityDescriptionEdge!]!

}

type AbilityDescriptionEdge implements Edge {  
  node: Description!

  versionGroupCode: String!
}

# EFFECT

type AbilityEffectConnection implements Connection {
  id: String!
  count: Int!
  
  edges: [AbilityEffectEdge!]! 
}

type AbilityEffectEdge implements Edge {  
  node: Effect!
}

# FIELD STATE

type AbilityActivatedByFieldStateConnection implements Connection {
  id: String!
  count: Int!
  
  edges: [AbilityActivatedByFieldStateEdge!]! 
}

type AbilityActivatedByFieldStateEdge implements Edge {  
  node: FieldState!
}

type AbilityCreatesFieldStateConnection implements Connection {
  id: String!
  count: Int!
  
  edges: [AbilityCreatesFieldStateEdge!]! 
}

type AbilityCreatesFieldStateEdge implements Edge {  
  node: FieldState!

  """
  The number of turns that the FieldState is present when created by the Ability. '0' implies the FieldState either lasts indefinitely until overwritten, or is present as long as the source is present (e.g. Primal Kyogre's Primordial Sea).
  """
  turns: Int!
}

type AbilityIgnoresFieldStateConnection implements Connection {
  id: String!
  count: Int!
  
  edges: [AbilityIgnoresFieldStateEdge!]! 
}

type AbilityIgnoresFieldStateEdge implements Edge {  
  node: FieldState!
}

type AbilityPreventsFieldStateConnection implements Connection {
  id: String!
  count: Int!
  
  edges: [AbilityPreventsFieldStateEdge!]! 
}

type AbilityPreventsFieldStateEdge implements Edge {  
  node: FieldState!
}

type AbilityRemovesFieldStateConnection implements Connection {
  id: String!
  count: Int!
  
  edges: [AbilityRemovesFieldStateEdge!]! 
}

type AbilityRemovesFieldStateEdge implements Edge {  
  node: FieldState!
}

type AbilitySuppressesFieldStateConnection implements Connection {
  id: String!
  count: Int!
  
  edges: [AbilitySuppressesFieldStateEdge!]! 
}

type AbilitySuppressesFieldStateEdge implements Edge {  
  node: FieldState!
}

# GENERATION

type AbilityGenerationConnection implements Connection {
  id: String!
  edges: [AbilityGenerationEdge!]! 

}

type AbilityGenerationEdge implements Edge {  
  node: Generation!
}

type AbilityIntroductionConnection implements Connection {
  id: String!
  edges: [AbilityIntroductionEdge!]! 

}

type AbilityIntroductionEdge implements Edge {  
  node: Generation!
}

# POKEMON

type AbilityPokemonConnection implements Connection {
  id: String!
  count: Int!
  
  edges: [AbilityPokemonEdge!]!

}

type AbilityPokemonEdge implements Edge {  
  node: Pokemon!
  slot: AbilitySlot!
}

# STAT

type AbilityModifiesStatConnection implements Connection {
  id: String!
  count: Int!
  
  edges: [AbilityModifiesStatEdge!]!

}

type AbilityModifiesStatEdge implements StatModificationEdge & Edge {  
  node: Stat!

  """
  An integer between -6 and 6 (except for moves which max out a stat, e.g. 'anger_point', in which case is 12). Null if the Ability modifies Stat via a multiplier.
  """
  stage: Int

  """
  Null if the Ability modifies Stat via a stage increase or decrease.
  """
  multiplier: Float

  """
  The probability of the Stat modification occurring once the necessary conditions have been met.
  
  For example, once rain is present for 'swift_swim', the speed boost is guaranteed to occur, so the 'chance' is 100.0.
  """
  chance: Float!

  """
  The recipient of the Stat modification.
  """
  recipient: StatModificationRecipient!
}

# STATUS

type AbilityCausesStatusConnection implements Connection {
  id: String!
  count: Int!
  
  edges: [AbilityCausesStatusEdge!]!

}

type AbilityCausesStatusEdge implements StatusCauseEdge & Edge {  
  node: Status!

  """
  The probability of the Ability causing the Status once the necessary conditions have been met. 

  For example, 'static' causing 'paralysis' has a 'chance' of 30.0 since that is the probability of the user of a Move being paralyzed, assuming the Move makes contact (a necessary condition for 'static').
  """
  chance: Float!
}

type AbilityResistsStatusConnection implements Connection {
  id: String!
  count: Int!
  
  edges: [AbilityResistsStatusEdge!]!

}

type AbilityResistsStatusEdge implements Edge {  
  node: Status!
}

# TYPE

type AbilityBoostsTypeConnection implements Connection {
  id: String!
  count: Int!
  
  edges: [AbilityBoostsTypeEdge!]!

}

type AbilityBoostsTypeEdge implements MultiplierEdge & Edge {  
  node: Type!

  """
  The multiplier by which the Ability boosts the power of Moves which have the Type. 
  """
  multiplier: Float!
}

type AbilityResistsTypeConnection implements Connection {
  id: String!
  count: Int!
  
  edges: [AbilityResistsTypeEdge!]!

}

type AbilityResistsTypeEdge implements Edge {  
  node: Type!

  """
  The multiplier by which the Ability resists the power of Moves which have the Type. 
  """
  multiplier: Float!
}

# USAGE METHOD

type AbilityActivatedByUsageMethodConnection implements Connection {
  id: String!
  count: Int!
  
  edges: [AbilityActivatedByUsageMethodEdge!]! 
}

type AbilityActivatedByUsageMethodEdge implements Edge {  
  node: UsageMethod!
}

type AbilityBoostsUsageMethodConnection implements Connection {
  id: String!
  count: Int!
  
  edges: [AbilityBoostsUsageMethodEdge!]!

}

type AbilityBoostsUsageMethodEdge implements MultiplierEdge & Edge {  
  node: UsageMethod!

  """
  The multiplier by which the Ability boosts the power of Moves which have the UsageMethod. 
  """
  multiplier: Float!
}

type AbilityPreventsUsageMethodConnection implements Connection {
  id: String!
  count: Int!
  
  edges: [AbilityPreventsUsageMethodEdge!]! 
}

type AbilityPreventsUsageMethodEdge implements Edge {  
  node: UsageMethod!
}

type AbilityResistsUsageMethodConnection implements Connection {
  id: String!
  count: Int!
  
  edges: [AbilityResistsUsageMethodEdge!]!

}

type AbilityResistsUsageMethodEdge implements Edge {  
  node: UsageMethod!

  """
  The multiplier by which the Ability resists the power of Moves which have the UsageMethod. 
  """
  multiplier: Float!
}

#
# ENUMS
#

enum AbilitySlot {
  ONE
  TWO
  HIDDEN
}

enum AbilityColumnNames {
  GEN
  ID
  NAME
  FORMATTED_NAME
  INTRODUCED
  POKEMON_SHOWDOWN_ID
}

#
# INPUTS
# 

input AbilityPaginationInput {
  limit: Int = 20
  offset: Int = 0
  orderBy: AbilityColumnNames = POKEMON_SHOWDOWN_ID
  sortBy: SortByEnum = ASC
  search: String = ""
}

input AbilityFilter {
  """
  The number of the Generation in which the Ability was introduced.
  """
  introduced: Int

  """
  The number of the Generation after which the Ability was introduced, inclusive.
  """
  introducedAfter: Int

  """
  The number of the Generation before which the Ability was introduced, inclusive.
  """
  introducedBefore: Int

  """
  The name of the Ability in snake_case.
  """
  name: String
  
  names: [String]

  """
  Abilities whose PSID contains the given string, case-insensitive.
  """
  contains: String

  """
  Abilities whose PSID ends with the given string, case-insensitive.
  """
  endsWith: String

  """
  Abilities whose PSID starts with the given string, case-insensitive.
  """
  startsWith: String
}