#
# QUERIES
#

extend type Query {
  descriptionByID(id: ID!): Description!

  descriptionsByEntityClass(class: DescriptionEntityClass!): [Description!]!

  descriptionsByEntityName(name: ID!): [Description!]!

  """
  Select Descriptions, with optional cursor-based pagination.
  """
  descriptions(
    pagination: PaginationInput
    filter: DescriptionFilter
  ): [Description!]!
}

#
# NODES AND HELPER TYPES
#

type Description implements Node {
  id: ID!

  """
  The entity to which the Description applies.
  """
  entity: DescriptionEntityConnection

  """
  The class of entity that the Description is describing, e.g. 'ITEM'.
  """ 
  entityClass: DescriptionEntityClass!

  """
  The name of the entity that the Description is describing, e.g. 'venusaurite'.
  """ 
  entityName: String!

  """
  The text of the Description as it appears on in-game/on Bulbapedia.
  """
  text: String!

  """
  The VersionGroup(s) in which the Description is present.
  """
  versionGroups: DescriptionVersionGroupConnection
}

#
# CONNECTIONS AND EDGES
#

# ABILITY

type DescriptionAbilityConnection implements Connection {
  count(filter: AbilityFilter): Int!
  
  edges(
    pagination: PaginationInput
    filter: AbilityFilter
  ): [DescriptionAbilityEdge!]!

}

type DescriptionAbilityEdge implements Edge {  
  node: Ability!

  versionGroups(
    pagination: PaginationInput
    filter: VersionGroupFilter
  ): [VersionGroup!]!
}

# ITEM

type DescriptionItemConnection implements Connection {
  count(filter: ItemFilter): Int!
  
  edges(
    pagination: PaginationInput
    filter: ItemFilter
  ): [DescriptionItemEdge!]!

}

type DescriptionItemEdge implements Edge {  
  node: Item!

  versionGroups(
    pagination: PaginationInput
    filter: VersionGroupFilter
  ): [VersionGroup!]!
}

# MOVE 

type DescriptionMoveConnection implements Connection {
  count(filter: MoveFilter): Int!
  
  edges(
    pagination: PaginationInput
    filter: MoveFilter
  ): [DescriptionMoveEdge!]!

}

type DescriptionMoveEdge implements Edge {  
  node: Move!

  versionGroups(
    pagination: PaginationInput
    filter: VersionGroupFilter
  ): [VersionGroup!]!
}

# VERSION GROUP 

type DescriptionVersionGroupConnection implements Connection {
  count(filter: VersionGroupFilter): Int!
  
  edges(
    pagination: PaginationInput
    filter: VersionGroupFilter
  ): [DescriptionVersionGroupEdge!]!

}

type DescriptionVersionGroupEdge implements Edge {  
  node: VersionGroup!
}

#
# ENUMS
#

"""
The type of entity that the Description is describing.
"""
enum DescriptionEntityClass {
  ABILITY
  ITEM
  MOVE
}

#
# UNIONS 
#

union DescriptionEntityConnection = DescriptionAbilityConnection | DescriptionItemConnection | DescriptionMoveConnection

#
# INPUTS
#

input DescriptionFilter {
  """
  The number of the Generation in which the Description was introduced.
  """
  introduced: Int

  """
  The number of the Generation after which the Description was introduced, inclusive.
  """
  introducedAfter: Int

  """
  The number of the Generation before which the Description was introduced, inclusive.
  """
  introducedBefore: Int

  """
  The name of the Description in snake_case.
  """
  name: String

  """
  Entities whose name contains the given string, case-insensitive.
  """
  contains: String

  """
  Entities whose name ends with the given string, case-insensitive.
  """
  endsWith: String

  """
  Entities whose name starts with the given string, case-insensitive.
  """
  startsWith: String
}