#
# QUERIES
#

extend type Query {
  generationByID(id: ID!): Generation!

  """
  Select a Generation by its arabic numeral, e.g. '1'.
  """
  generationByNumber(number: Int!): Generation!

  """
  Select a Generation by its roman numerical code, e.g. 'ii' or 'III' (case doesn't matter).
  """
  generationByCode(code: String!): Generation!

  """
  Select Generations, with optional cursor-based pagination.
  """
  generations(
    pagination: PaginationInput
    filter: GenerationFilter
  ): [Generation!]!
}

#
# NODES AND HELPER TYPES
#

"""
A grouping of the 'Pokemon' games (further divided into VersionGroups), separated based on the Pokemon that the Generation includes. 
"""
type Generation implements Node {
  id: ID!

  """
  All Abilities present in this Generation.
  """
  abilities: GenerationAbilityConnection

  """
  All Abilities introduced in this Generation.
  """
  abilitiesIntroduced: GenerationIntroducedAbilityConnection

  """
  All Effects present in this Generation.
  """
  effects: GenerationEffectConnection

  """
  All Effects introduced in this Generation.
  """
  effectsIntroduced: GenerationIntroducedEffectConnection

  """
  All FieldStates present in this Generation.
  """
  fieldStates: GenerationFieldStateConnection

  """
  All FieldStates introduced in this Generation.
  """
  fieldStatesIntroduced: GenerationIntroducedFieldStateConnection

  """
  The roman numeral for the Generation.
  """
  code: GenerationCode!

  """
  The literal number of the Generation (e.g. '1' for Generation 1, '2' for Generation 2, etc.).
  """
  number: Int!

  """
  All Items present in this Generation.
  """
  items: GenerationItemConnection

  """
  All Items present in this Generation.
  """
  itemsIntroduced: GenerationIntroducedItemConnection

  """
  All Moves present in this Generation.
  """
  moves: GenerationMoveConnection

  """
  All Moves introduced in this Generation.
  """
  movesIntroduced: GenerationIntroducedMoveConnection

  """
  All Pokemon present in this Generation.
  """
  pokemon: GenerationPokemonConnection

  """
  All Pokemon introduced in this Generation.
  """
  pokemonIntroduced: GenerationIntroducedPokemonConnection

  """
  All Stats present in this Generation.
  """
  stats: GenerationStatConnection

  """
  All Stats introduced in this Generation.
  """
  statsIntroduced: GenerationIntroducedStatConnection

  """
  All Statuses present in this Generation.
  """
  statuses: GenerationStatusConnection

  """
  All Statuses introduced in this Generation.
  """
  statusesIntroduced: GenerationIntroducedStatusConnection

  """
  All Types present in this Generation.
  """
  types: GenerationTypeConnection

  """
  All Types introduced in this Generation.
  """
  typesIntroduced: GenerationIntroducedTypeConnection

  """
  All UsageMethods present in this Generation.
  """
  usageMethods: GenerationUsageMethodConnection

  """
  All UsageMethods introduced in this Generation.
  """
  usageMethodsIntroduced: GenerationIntroducedUsageMethodConnection

  """
  All VersionGroups present in this Generation.
  """
  versionGroups: GenerationVersionGroupConnection

  """
  All VersionGroups introduced in this Generation.
  """
  versionGroupsIntroduced: GenerationIntroducedVersionGroupConnection
}

#
# CONNECTIONS AND EDGES
#

# ABILITY

type GenerationAbilityConnection implements Connection {
  count: Int!
  
  edges(
    pagination: PaginationInput
    filter: AbilityFilter
  ): [GenerationAbilityEdge!]! 

}

type GenerationIntroducedAbilityConnection implements Connection {
  count: Int!
  
  edges(
    pagination: PaginationInput
    filter: AbilityFilter
  ): [GenerationAbilityEdge!]! 

}

type GenerationAbilityEdge implements Edge {  
  node: Ability!
}

# EFFECT

type GenerationEffectConnection implements Connection {
  count: Int!
  
  edges(
    pagination: PaginationInput
    filter: EffectFilter
  ): [GenerationEffectEdge!]! 

}

type GenerationIntroducedEffectConnection implements Connection {
  count: Int!
  
  edges(
    pagination: PaginationInput
    filter: EffectFilter
  ): [GenerationEffectEdge!]! 

}

type GenerationEffectEdge implements Edge {  
  node: Effect!
}

# FIELD STATE

type GenerationFieldStateConnection implements Connection {
  count: Int!
  
  edges(
    pagination: PaginationInput
    filter: FieldStateFilter
  ): [GenerationFieldStateEdge!]! 

}

type GenerationIntroducedFieldStateConnection implements Connection {
  count: Int!
  
  edges(
    pagination: PaginationInput
    filter: FieldStateFilter
  ): [GenerationFieldStateEdge!]! 

}

type GenerationFieldStateEdge implements Edge {  
  node: FieldState!
}


# ITEM

type GenerationItemConnection implements Connection {
  count: Int!
  
  edges(
    pagination: PaginationInput
    filter: ItemFilter
  ): [GenerationItemEdge!]! 

}

type GenerationIntroducedItemConnection implements Connection {
  count: Int!
  
  edges(
    pagination: PaginationInput
    filter: ItemFilter
  ): [GenerationItemEdge!]! 

}

type GenerationItemEdge implements Edge {  
  node: Item!
}

# MOVE

type GenerationMoveConnection implements Connection {
  count: Int!
  
  edges(
    pagination: PaginationInput
    filter: MoveFilter
  ): [GenerationMoveEdge!]! 

}

type GenerationIntroducedMoveConnection implements Connection {
  count: Int!
  
  edges(
    pagination: PaginationInput
    filter: MoveFilter
  ): [GenerationMoveEdge!]! 

}

type GenerationMoveEdge implements Edge {  
  node: Move!
}

# POKEMON

type GenerationPokemonConnection implements Connection {
  count: Int!
  
  edges(
    pagination: PaginationInput
    filter: PokemonFilter
  ): [GenerationPokemonEdge!]! 

}

type GenerationIntroducedPokemonConnection implements Connection {
  count: Int!
  
  edges(
    pagination: PaginationInput
    filter: PokemonFilter
  ): [GenerationPokemonEdge!]! 

}

type GenerationPokemonEdge implements Edge {  
  node: Pokemon!
}

# STAT

type GenerationStatConnection implements Connection {
  count: Int!
  
  edges(
    pagination: PaginationInput
    filter: StatFilter
  ): [GenerationStatEdge!]! 

}

type GenerationIntroducedStatConnection implements Connection {
  count: Int!
  
  edges(
    pagination: PaginationInput
    filter: StatFilter
  ): [GenerationStatEdge!]! 

}

type GenerationStatEdge implements Edge {  
  node: Stat!
}

# STATUS

type GenerationStatusConnection implements Connection {
  count: Int!
  
  edges(
    pagination: PaginationInput
    filter: StatusFilter
  ): [GenerationStatusEdge!]! 

}

type GenerationIntroducedStatusConnection implements Connection {
  count: Int!
  
  edges(
    pagination: PaginationInput
    filter: StatusFilter
  ): [GenerationStatusEdge!]! 

}

type GenerationStatusEdge implements Edge {  
  node: Status!
}

# TYPE

type GenerationTypeConnection implements Connection {
  count: Int!
  
  edges(
    pagination: PaginationInput
    filter: TypeFilter
  ): [GenerationTypeEdge!]! 

}

type GenerationIntroducedTypeConnection implements Connection {
  count: Int!
  
  edges(
    pagination: PaginationInput
    filter: TypeFilter
  ): [GenerationTypeEdge!]! 

}

type GenerationTypeEdge implements Edge {  
  node: Type!
}

# USAGE METHOD

type GenerationUsageMethodConnection implements Connection {
  count: Int!
  
  edges(
    pagination: PaginationInput
    filter: UsageMethodFilter
  ): [GenerationUsageMethodEdge!]! 

}

type GenerationIntroducedUsageMethodConnection implements Connection {
  count: Int!
  
  edges(
    pagination: PaginationInput
    filter: UsageMethodFilter
  ): [GenerationUsageMethodEdge!]! 

}

type GenerationUsageMethodEdge implements Edge {  
  node: UsageMethod!
}

# VERSION GROUP

type GenerationVersionGroupConnection implements Connection {
  count: Int!
  
  edges(
    pagination: PaginationInput
    filter: VersionGroupFilter
  ): [GenerationVersionGroupEdge!]! 

}

type GenerationIntroducedVersionGroupConnection implements Connection {
  count: Int!
  
  edges(
    pagination: PaginationInput
    filter: VersionGroupFilter
  ): [GenerationVersionGroupEdge!]! 

}

type GenerationVersionGroupEdge implements Edge {  
  node: VersionGroup!
}

#
# ENUMS
#

"""
A roman numeral for the Generation.
""" 
enum GenerationCode {
  I
  II
  III
  IV
  V
  VI
  VII
  VIII
  IX
  X
}

#
# INPUTS
#

input GenerationFilter {
  """
  The number of the Generation in which the Generation was introduced.
  """
  introduced: Int

  """
  The number of the Generation after which the Generation was introduced, inclusive.
  """
  introducedAfter: Int

  """
  The number of the Generation before which the Generation was introduced, inclusive.
  """
  introducedBefore: Int

  """
  The name of the Generation in snake_case.
  """
  name: String

  """
  Entities whose name contains the given string, case-insensitive.
  """
  contains: String

  """
  Entities whose name ends with the given string, case-insensitive.
  """
  endsWith: String

  """
  Entities whose name starts with the given string, case-insensitive.
  """
  startsWith: String


  # OTHER FILTERS


  
}