#
# QUERIES
#

extend type Query {
  itemByID(id: ID!): Item!

  """
  Select a Item by its snake_case name, e.g. 'venusaurite', 'firium_z'.
  """
  itemByName(generation: Int = 8, name: String!): Item!
  
  """
  Select Items, with optional cursor-based pagination.

  'generation' refers to the (number of the) Generation in which to consider the Item. Defaults to the latest Generation.

  'introducedAfter' and 'introducedBefore' refer to the number of a Generation, and are inclusive.

  'startsWith', 'contains', 'endsWith' refer to the name, and are case-insensitive.

  'itemClass' is a case-insensitive.tring, with words separated by underscores, e.g. 'mega_stone', 'z_crystal'. See the ItemClass enum for all possibilities.

  """
  items(
    generation: Int = 8
    pagination: PaginationInput
    filter: ItemFilter
  ): [Item!]!
}

#
# NODES AND HELPER TYPES
#

type Item implements Node {
  id: ID!

  """
  E.g. 'electric_terrain' activates 'electric_seed'.
  """
  activatedByFieldState: ItemActivatedByFieldStateConnection

  boostsType: ItemBoostsTypeConnection

  boostsUsageMethod: ItemBoostsUsageMethodConnection

  causesStatus: ItemCausesStatusConnection

  class: ItemClass

  """
  The Descriptions for the Move across the different VersionGroups.
  """
  descriptions: ItemDescriptionConnection

  effects: ItemEffectConnection

  """
  Entities which the Item enables.
  """
  enables: ItemEnablesConnection

  """
  E.g. Z-Crystals enable their corresponding Z-Moves.
  """
  enablesMove: ItemEnablesMoveConnection

  """
  E.g. Mega Stones enable their corresponding mega-evolved Pokemon.
  """
  enablesPokemon: ItemEnablesPokemonConnection

  extendsFieldState: ItemExtendsFieldStateConnection

  """
  The formatted name of the Item, with correct punctuation.
  """
  formattedName: String!

  """
  The Generation of this Item.
  """ 
  generation: ItemGenerationConnection

  ignoresFieldState: ItemIgnoresFieldStateConnection

  """
  The Generation in which the Item was introduced.
  """
  introduced: ItemIntroductionConnection

  modifiesStat: ItemModifiesStatConnection

  """
  The name of the Item in snake_case. Hyphens are converted to underscores.
  """
  name: String!

  """
  Describes the Type and power of the Move Natural Gift when the user holds the Item.
  """
  naturalGift: ItemNaturalGiftConnection

  """
  Entities which the Item requires.
  """
  requires: ItemRequiresPokemonConnection

  """
  The Pokemon necessary for this item to take effect.

  For example:
    Only Venusaur can use Venasaurite to Mega-evolve.
    Only Latias and Latios can obtain the effects of Soul Dew.
  """
  requiresPokemon: ItemRequiresPokemonConnection

  resistsFieldState: ItemResistsFieldStateConnection

  resistsStatus: ItemResistsStatusConnection

  resistsType: ItemResistsTypeConnection

  resistsUsageMethod: ItemResistsUsageMethodConnection

}

#
# CONNECTIONS AND EDGES
#

# DESCRIPTION 

type ItemDescriptionConnection implements Connection {
  count(filter: DescriptionFilter): Int!
  
  edges(
    pagination: PaginationInput
    filter: DescriptionFilter
  ): [ItemDescriptionEdge!]!

}

type ItemDescriptionEdge implements Edge {  
  node: Description!
}

# EFFECT

type ItemEffectConnection implements Connection {
  count(filter: EffectFilter): Int!
  
  edges(
    pagination: PaginationInput
    filter: EffectFilter
  ): [ItemEffectEdge!]! 

}

type ItemEffectEdge implements Edge {  
  node: Effect!
}

# FIELD STATE

type ItemActivatedByFieldStateConnection implements Connection {
  count(filter: FieldStateFilter): Int!
  
  edges(
    pagination: PaginationInput
    filter: FieldStateFilter
  ): [ItemActivatedByFieldStateEdge!]! 

}

type ItemActivatedByFieldStateEdge implements Edge {  
  node: FieldState!
}

type ItemExtendsFieldStateConnection implements Connection {
  count(filter: FieldStateFilter): Int!
  
  edges(
    pagination: PaginationInput
    filter: FieldStateFilter
  ): [ItemExtendsFieldStateEdge!]! 

}

type ItemExtendsFieldStateEdge implements Edge {  
  node: FieldState!

  """
  E.g. 'damp_rock' makes 'rain' last for 8 turns rather than 5.
  """
  turns: Int!
}

type ItemIgnoresFieldStateConnection implements Connection {
  count(filter: FieldStateFilter): Int!
  
  edges(
    pagination: PaginationInput
    filter: FieldStateFilter
  ): [ItemIgnoresFieldStateEdge!]! 

}

type ItemIgnoresFieldStateEdge implements Edge {  
  node: FieldState!
}

type ItemResistsFieldStateConnection implements Connection {
  count(filter: FieldStateFilter): Int!
  
  edges(
    pagination: PaginationInput
    filter: FieldStateFilter
  ): [ItemResistsFieldStateEdge!]! 

}

type ItemResistsFieldStateEdge implements Edge {  
  node: FieldState!

  multiplier: Float!
}

# GENERATION

type ItemGenerationConnection implements Connection {
  edges(
    pagination: PaginationInput
    filter: GenerationFilter
  ): [ItemGenerationEdge!]! 

}

type ItemGenerationEdge implements Edge {  
  node: Generation!
}

type ItemIntroductionConnection implements Connection {
  edges(
    pagination: PaginationInput
    filter: GenerationFilter
  ): [ItemIntroductionEdge!]! 

}

type ItemIntroductionEdge implements Edge {  
  node: Generation!
}

# MOVE

type ItemEnablesMoveConnection implements Connection {
  count(filter: MoveFilter): Int!
  
  edges(
    pagination: PaginationInput
    filter: MoveFilter
  ): [ItemEnablesMoveEdge!]!

}

type ItemEnablesMoveEdge implements Edge {  
  node: Move!
}

# POKEMON

type ItemEnablesPokemonConnection implements Connection {
  count(filter: PokemonFilter): Int!
  
  edges(
    pagination: PaginationInput
    filter: PokemonFilter
  ): [ItemEnablesPokemonEdge!]!

}

type ItemEnablesPokemonEdge implements Edge {  
  node: Pokemon!
}

type ItemRequiresPokemonConnection implements Connection {
  count(filter: PokemonFilter): Int!
  
  edges(
    pagination: PaginationInput
    filter: PokemonFilter
  ): [ItemRequiresPokemonEdge!]!

}

type ItemRequiresPokemonEdge implements Edge {  
  node: Pokemon!
}

# STAT

type ItemModifiesStatConnection implements Connection {
  count(filter: StatFilter): Int!
  
  edges(
    pagination: PaginationInput
    filter: StatFilter
  ): [ItemModifiesStatEdge!]!

}

type ItemModifiesStatEdge implements Edge {  
  node: Stat!

  """
  An integer between -6 and 6. Null if the Item modifies Stat via a multiplier.
  """
  stage: Int

  """
  Null if the Item modifies Stat via a stage increase or decrease.
  """
  multiplier: Float

  """
  The probability of the Stat modification occurring once the necessary conditions have been met.
  
  For example, once a Pokemon has fallen bellow quarter health, stat-boosting berries are guaranteed to give a stat boost, so the 'chance' is 100.0.
  """
  chance: Float!

  """
  The recipient of the Stat modification.
  """
  recipient: Recipient!
}

# STATUS

type ItemCausesStatusConnection implements Connection {
  count(filter: StatusFilter): Int!
  
  edges(
    pagination: PaginationInput
    filter: StatusFilter
  ): [ItemCausesStatusEdge!]!

}

type ItemCausesStatusEdge implements Edge {  
  node: Status!

  """
  The probability of the Item causing the Status once the necessary conditions have been met.
  """
  chance: Float!
}

type ItemResistsStatusConnection implements Connection {
  count(filter: StatusFilter): Int!
  
  edges(
    pagination: PaginationInput
    filter: StatusFilter
  ): [ItemResistsStatusEdge!]!

}

type ItemResistsStatusEdge implements Edge {  
  node: Status!
}

# TYPE

type ItemBoostsTypeConnection implements Connection {
  count(filter: TypeFilter): Int!
  
  edges(
    pagination: PaginationInput
    filter: TypeFilter
  ): [ItemBoostsTypeEdge!]!

}

type ItemBoostsTypeEdge implements Edge {  
  node: Type!

  """
  The multiplier by which the Item boosts the power of Moves which have the Type. 
  """
  multiplier: Float!
}

type ItemResistsTypeConnection implements Connection {
  count(filter: TypeFilter): Int!
  
  edges(
    pagination: PaginationInput
    filter: TypeFilter
  ): [ItemResistsTypeEdge!]!

}

type ItemResistsTypeEdge implements Edge {  
  node: Type!

  """
  The multiplier by which the Item resists the power of Moves which have the Type. 
  """
  multiplier: Float!
}

type ItemNaturalGiftConnection implements Connection {
  count(filter: TypeFilter): Int!
  
  edges(
    pagination: PaginationInput
    filter: TypeFilter
  ): [ItemNaturalGiftEdge!]!

}

type ItemNaturalGiftEdge implements Edge {  
  node: Type!

  """
  The power of Natural Gift when used by a Pokemon holding Item.
  """
  power: Int!
}

# USAGE METHOD

type ItemBoostsUsageMethodConnection implements Connection {
  count(filter: UsageMethodFilter): Int!
  
  edges(
    pagination: PaginationInput
    filter: UsageMethodFilter
  ): [ItemBoostsUsageMethodEdge!]!

}

type ItemBoostsUsageMethodEdge implements Edge {  
  node: UsageMethod!

  """
  The multiplier by which the Item boosts the power of Moves which have the UsageMethod. 
  """
  multiplier: Float!
}

type ItemResistsUsageMethodConnection implements Connection {
  count(filter: UsageMethodFilter): Int!
  
  edges(
    pagination: PaginationInput
    filter: UsageMethodFilter
  ): [ItemResistsUsageMethodEdge!]!

}

type ItemResistsUsageMethodEdge implements Edge {  
  node: UsageMethod!

  """
  The multiplier by which the Item resists the power of Moves which have the UsageMethod. 
  """
  multiplier: Float!
}

#
# ENUMS
#

enum ItemClass {
  BERRY
  CHOICE
  DRIVE
  GEM
  INCENSE
  MEGA_STONE
  MEMORY
  OTHER
  PLATE
  POWER
  STAT_ENHANCER
  TYPE_ENHANCER
  Z_CRYSTAL
}

#
# UNIONS
#

union ItemEnablesConnection = ItemEnablesMoveConnection | ItemEnablesPokemonConnection

#
# INPUTS
#

input ItemFilter {
  """
  The number of the Generation in which the Item was introduced.
  """
  introduced: Int

  """
  The number of the Generation after which the Item was introduced, inclusive.
  """
  introducedAfter: Int

  """
  The number of the Generation before which the Item was introduced, inclusive.
  """
  introducedBefore: Int

  """
  The name of the Item in snake_case.
  """
  name: String

  """
  Entities whose name contains the given string, case-insensitive.
  """
  contains: String

  """
  Entities whose name ends with the given string, case-insensitive.
  """
  endsWith: String

  """
  Entities whose name starts with the given string, case-insensitive.
  """
  startsWith: String


  # OTHER FILTERS

  
}