#
# QUERIES
#

extend type Query {
  statusByID(id: ID!): Status!

  """
  Select a Status by its snake_case name, e.g. 'center_of_attention'.
  """
  statusByName(name: String!): Status!
  
  """
  Select Statuses, with optional cursor-based pagination.

  'introducedAfter' and 'introducedBefore' refer to the number of a Generation, and are inclusive.

  'startsWith', 'contains', 'endsWith' refer to the name, and are case-insensitive.
  """
  statuses(
    cursor: String,
    limit: Int,
    contains: String,
    endsWith: String,
    introducedAfter: Int,
    introducedBefore: Int,
    startsWith: String,
  ): [Status!]!
}

#
# NODES AND HELPER TYPES
#

type Status implements Node {
  id: ID!

  abilityCauses(input: ConnectionInput): StatusCausedByAbilityConnection

  abilityResists(input: ConnectionInput): StatusResistedByAbilityConnection

  """
  The name of the Status in Title Case, with appropriate punctuation.
  """
  formattedName: String!

  itemCauses(input: ConnectionInput): StatusCausedByItemConnection

  itemResists(input: ConnectionInput): StatusResistedByItemConnection

  moveCauses(input: ConnectionInput): StatusCausedByMoveConnection

  """
  Refers to Moves which either cure or alleviate the negative effects of Status conditions. For example, 'heal_bell' cannot prevent the 'burn' status, but it can heal it. We bring it under 'resistsStatus' rather than splitting it off into its own field like 'healsStatus'. 
  """
  moveResists(input: ConnectionInput): StatusResistedByMoveConnection

  """
  The name of the Status in snake_case.
  """
  name: String!
}

#
# CONNECTIONS AND EDGES
#

# ABILITY

type StatusCausedByAbilityConnection implements Connection {
  edges: [StatusCausedByAbilityEdge!]!
  pageInfo: PageInfo!
}

type StatusCausedByAbilityEdge implements Edge {
  cursor: String!
  node: Ability!
  
  """
  The probability of the Ability causing the Status once the necessary conditions have been met. 

  For example, 'static' causing 'paralysis' has a 'chance' of 30.0 since that is the probability of the user of a Move being paralyzed, assuming the Move makes contact (a necessary condition for 'static').
  """
  chance: Float!
}

type StatusResistedByAbilityConnection implements Connection {
  edges: [StatusResistedByAbilityEdge!]!
  pageInfo: PageInfo!
}

type StatusResistedByAbilityEdge implements Edge {
  cursor: String!
  node: Ability!
}

# ITEM

type StatusCausedByItemConnection implements Connection {
  edges: [StatusCausedByItemEdge!]!
  pageInfo: PageInfo!
}

type StatusCausedByItemEdge implements Edge {
  cursor: String!
  node: Item!
  
  """
  The probability of the Item causing the Status once the necessary conditions have been met.
  """
  chance: Float!
}

type StatusResistedByItemConnection implements Connection {
  edges: [StatusResistedByItemEdge!]!
  pageInfo: PageInfo!
}

type StatusResistedByItemEdge implements Edge {
  cursor: String!
  node: Item!
}

# MOVE

type StatusCausedByMoveConnection implements Connection {
  edges: [StatusCausedByMoveEdge!]!
  pageInfo: PageInfo!
}

type StatusCausedByMoveEdge implements Edge {
  cursor: String!
  node: Move!
  
  """
  The probability of the Move causing the Status once the necessary conditions have been met (i.e. the move being successful/hitting).
  """
  chance: Float!
}

type StatusResistedByMoveConnection implements Connection {
  edges: [StatusResistedByMoveEdge!]!
  pageInfo: PageInfo!
}

type StatusResistedByMoveEdge implements Edge {
  cursor: String!
  node: Move!
}