#
# QUERIES
#

extend type Query {
  """
  Select a Type by its snake_case name, e.g. 'dark'.
  """
  typeByName(
    generation: Int = 8
    generations: [Int]
    name: String!
  ): [Type!]!

  """
  Select Types by their snake_case name, e.g. 'dark'.
  """
  typesByName(
    generation: Int = 8
    generations: [Int]
    names: [String!]!
  ): [Type!]!
  
  """
  Select Types, with optional cursor-based pagination.

  'generation' refers to the (number of the) Generation in which to consider the Type. Defaults to the latest Generation.

  'introducedAfter' and 'introducedBefore' refer to the number of a Generation, and are inclusive.

  'startsWith', 'contains', 'endsWith' refer to the name, and are case-insensitive.
  """
  types(
    generation: Int = 8
    generations: [Int]
    pagination: PaginationInput
    filter: TypeFilter
  ): [Type!]!
}

#
# NODES AND HELPER TYPES
#

type Type implements Node {
  id: ID!

  boostedByAbility(filter: AbilityFilter): TypeBoostedByAbilityConnection

  boostedByFieldState(filter: FieldStateFilter): TypeBoostedByFieldStateConnection

  boostedByItem(filter: ItemFilter): TypeBoostedByItemConnection

  """
  The matchups of this Type as the defending-type against other attacking Types.
  """
  defensiveMatchups(filter: TypeFilter): DefensiveTypeMatchupConnection

  """
  E.g. 'normal'-Type Moves enable 'breakneck_blitz'.
  """
  enablesMove(filter: MoveFilter): TypeEnablesMoveConnection

  """
  The name of the Type in Title Case.
  """
  formattedName: String!

  """
  The Generation of this Type.
  """ 
  generation(filter: GenerationFilter): TypeGenerationConnection

  """
  E.g. 'flying' Type Pokemon ignores 'spikes'.
  """
  ignoresFieldState(filter: FieldStateFilter): TypeIgnoresFieldStateConnection

  """
  The Generation in which the Type was introduced.
  """
  introduced(filter: GenerationFilter): TypeIntroductionConnection

  moves(filter: MoveFilter): TypeMoveConnection

  """
  The name of the Type in snake_case. 
  """
  name: String!

  """
  The Items which grant their holder a 'natural_gift' of this Type.
  """
  naturalGift(filter: ItemFilter): TypeNaturalGiftConnection

  """
  The matchups of this Type as the attacking-type against other defending Types.
  """
  offensiveMatchups(filter: TypeFilter): OffensiveTypeMatchupConnection
  
  pokemon(filter: PokemonFilter): TypePokemonConnection

  """
  E.g. 'poison' Type Pokemon remove 'toxic_spikes' on entry.
  """
  removesFieldState(filter: FieldStateFilter): TypeRemovesFieldStateConnection

  resistedByAbility(filter: AbilityFilter): TypeResistedByAbilityConnection

  """
  E.g. 'harsh_sunlight' weakens 'water' Type Moves.
  """
  weakenedByFieldState(filter: FieldStateFilter): TypeWeakenedByFieldStateConnection

  resistedByItem(filter: ItemFilter): TypeResistedByItemConnection

  """
  E.g. 'ground' Type Pokemon take less damage from the 'stealth_rock' FieldState. 'fairy' Type Pokemon take more damage from 'sharp_steel', but we still group it in this category rather than add an extra field.
  """ 
  resistsFieldState(filter: FieldStateFilter): TypeResistsFieldStateConnection

  """
  FieldStates which turn 'weather_ball' to this Type.
  """
  weatherBall(filter: FieldStateFilter): TypeWeatherBallConnection
}

#
# CONNECTIONS AND EDGES
#

# ABILITY

type TypeBoostedByAbilityConnection implements Connection {
  id: String!
  count: Int!
  
  edges(
    pagination: PaginationInput
  ): [TypeBoostedByAbilityEdge!]!

}

type TypeBoostedByAbilityEdge implements MultiplierEdge & Edge {  
  node: Ability!
  multiplier: Float!
}

type TypeResistedByAbilityConnection implements Connection {
  id: String!
  count: Int!
  
  edges(
    pagination: PaginationInput
  ): [TypeResistedByAbilityEdge!]!

}

type TypeResistedByAbilityEdge implements Edge {  
  node: Ability!
  multiplier: Float!
}

# FIELD STATE

type TypeWeatherBallConnection implements Connection {
  id: String!
  count: Int!
  
  edges(
    pagination: PaginationInput
  ): [TypeWeatherBallEdge!]!

}

type TypeWeatherBallEdge implements Edge {  
  node: FieldState!
}

type TypeBoostedByFieldStateConnection implements Connection {
  id: String!
  count: Int!
  
  edges(
    pagination: PaginationInput
  ): [TypeBoostedByFieldStateEdge!]!

}

type TypeBoostedByFieldStateEdge implements MultiplierEdge & Edge {  
  node: FieldState!
  multiplier: Float!
}

type TypeWeakenedByFieldStateConnection implements Connection {
  id: String!
  count: Int!
  
  edges(
    pagination: PaginationInput
  ): [TypeWeakenedByFieldStateEdge!]!

}

type TypeWeakenedByFieldStateEdge implements Edge {  
  node: FieldState!
  multiplier: Float!
}

type TypeIgnoresFieldStateConnection implements Connection {
  id: String!
  count: Int!
  
  edges(
    pagination: PaginationInput
  ): [TypeIgnoresFieldStateEdge!]! 

}

type TypeIgnoresFieldStateEdge implements Edge {  
  node: FieldState!
}

type TypeResistsFieldStateConnection implements Connection {
  id: String!
  count: Int!
  
  edges(
    pagination: PaginationInput
  ): [TypeResistsFieldStateEdge!]! 

}

type TypeResistsFieldStateEdge implements Edge {  
  node: FieldState!

  multiplier: Float!
}

type TypeRemovesFieldStateConnection implements Connection {
  id: String!
  count: Int!
  
  edges(
    pagination: PaginationInput
  ): [TypeRemovesFieldStateEdge!]! 

}

type TypeRemovesFieldStateEdge implements Edge {  
  node: FieldState!
}

# GENERATION

type TypeGenerationConnection implements Connection {
  id: String!
  count: Int!
  
  edges(
    pagination: PaginationInput
  ): [TypeGenerationEdge!]! 

}

type TypeGenerationEdge implements Edge {  
  node: Generation!
}

type TypeIntroductionConnection implements Connection {
  id: String!
  count: Int!
  
  edges(
    pagination: PaginationInput
  ): [TypeIntroductionEdge!]! 

}

type TypeIntroductionEdge implements Edge {  
  node: Generation!
}

# ITEM

type TypeNaturalGiftConnection implements Connection {
  id: String!
  count: Int!
  
  edges(
    pagination: PaginationInput
  ): [TypeNaturalGiftEdge!]!

}

type TypeNaturalGiftEdge implements Edge {  
  node: Item!

  """
  The power of Natural Gift when used by a Pokemon holding Item.
  """
  power: Int!
}

type TypeBoostedByItemConnection implements Connection {
  id: String!
  count: Int!
  
  edges(
    pagination: PaginationInput
  ): [TypeBoostedByItemEdge!]!

}

type TypeBoostedByItemEdge implements MultiplierEdge & Edge {  
  node: Item!
  multiplier: Float!
}

type TypeResistedByItemConnection implements Connection {
  id: String!
  count: Int!
  
  edges(
    pagination: PaginationInput
  ): [TypeResistedByItemEdge!]!

}

type TypeResistedByItemEdge implements Edge {  
  node: Item!
  multiplier: Float!
}

# MOVE

type TypeMoveConnection implements Connection {
  id: String!
  count: Int!
  
  edges(
    pagination: PaginationInput
  ): [TypeMoveEdge!]!

}

type TypeMoveEdge implements Edge {  
  node: Move!
}

type TypeEnablesMoveConnection implements Connection {
  id: String!
  count: Int!
  
  edges(
    pagination: PaginationInput
  ): [TypeEnablesMoveEdge!]!

}

type TypeEnablesMoveEdge implements Edge {  
  node: Move!
}

# POKEMON

type TypePokemonConnection implements Connection {
  id: String!
  count: Int!
  
  edges(
    pagination: PaginationInput
  ): [TypePokemonEdge!]!

}

type TypePokemonEdge implements Edge {  
  node: Pokemon!
}

# TYPE

type DefensiveTypeMatchupConnection implements Connection {
  id: String!
  count: Int!
  
  edges(
    pagination: PaginationInput
  ): [DefensiveTypeMatchupEdge!]!

}

type DefensiveTypeMatchupEdge implements Edge {  
  node: Type!

  """
  The multiplier of the Type-matchup, with the starting node as the defendingType and the ending node as the attacking Type.
  """
  multiplier: Float!
}

type OffensiveTypeMatchupConnection implements Connection {
  id: String!
  count: Int!
  
  edges(
    pagination: PaginationInput
  ): [OffensiveTypeMatchupEdge!]!

}

type OffensiveTypeMatchupEdge implements Edge {  
  node: Type!

  """
  The multiplier of the Type-matchup, with the starting node as the attacking Type and the ending node as the defending Type.
  """
  multiplier: Float!
}

#
# INPUTS
#

input TypeFilter {
  """
  The number of the Generation in which the Type was introduced.
  """
  introduced: Int

  """
  The number of the Generation after which the Type was introduced, inclusive.
  """
  introducedAfter: Int

  """
  The number of the Generation before which the Type was introduced, inclusive.
  """
  introducedBefore: Int

  """
  The name of the Type in snake_case.
  """
  name: String
  
  names: [String]

  """
  Entities whose name contains the given string, case-insensitive.
  """
  contains: String

  """
  Entities whose name ends with the given string, case-insensitive.
  """
  endsWith: String

  """
  Entities whose name starts with the given string, case-insensitive.
  """
  startsWith: String
}