#
# QUERIES
#

extend type Query {
  typeByID(id: ID!): Type!

  """
  Select an Type by its snake_case name, e.g. 'rks_system'.
  """
  typeByName(name: String!): Type!
  
  """
  Select Types, with optional cursor-based pagination.

  'introducedAfter' and 'introducedBefore' refer to the number of a Generation, and are inclusive.

  'startsWith', 'contains', 'endsWith' refer to the name, and are case- and punctuation- insensitive.
  """
  types(
    cursor: String,
    limit: Int,
    contains: String,
    endsWith: String,
    introducedAfter: Int,
    introducedBefore: Int,
    startsWith: String,
  ): [Type!]!
}

#
# NODES AND HELPER TYPES
#

type Type implements Node {
  id: ID!

  abilityBoosts(input: ConnectionInput): TypeBoostedByAbilityConnection

  abilityResists(input: ConnectionInput): TypeResistedByAbilityConnection

  """
  Entities which the Type enables.
  """
  enables(input: ConnectionInput): TypeEnablesMoveConnection

  """
  E.g. 'normal'-Type Moves enable 'breakneck_blitz'.
  """
  enablesMove(input: ConnectionInput): TypeEnablesMoveConnection


  """
  The name of the Type in Title Case.
  """
  formattedName: String!

  """
  The Generation in which the Type was introduced.
  """
  introduced(input: ConnectionInput): TypeGenerationConnection

  itemBoosts(input: ConnectionInput): TypeBoostedByItemConnection

  itemResists(input: ConnectionInput): TypeResistedByItemConnection

  """
  The matchups of this Type as the attacking-type against other defending Types.
  """
  matchups(input: ConnectionInput): TypeMatchupConnection

  moves(input: ConnectionInput): TypeMoveConnection

  """
  The name of the Type in snake_case. 
  """ 
  name: String!

  """
  The Items which grant their holder a 'natural_gift' of this Type.
  """
  naturalGift(input: ConnectionInput): ItemNaturalGiftConnection

  pokemon(input: ConnectionInput): TypePokemonConnection

  #
  # CONVENIENCE FIELDS
  #
  
  """
  Convenience field for damage calculations. For pagination, use the 'matchups' field.
  """
  doubleDamageFrom: [Type!]!

  """
  Convenience field for damage calculations. For pagination, use the 'matchups' field.
  """
  neutralDamageFrom: [Type!]!

  """
  Convenience field for damage calculations. For pagination, use the 'matchups' field.
  """
  halfDamageFrom: [Type!]!

  """
  Convenience field for damage calculations. For pagination, use the 'matchups' field.
  """
  noDamageFrom: [Type!]!

  """
  Convenience field for damage calculations. For pagination, use the 'matchups' field.
  """
  doubleDamageTo: [Type!]!

  """
  Convenience field for damage calculations. For pagination, use the 'matchups' field.
  """
  neutralDamageTo: [Type!]!

  """
  Convenience field for damage calculations. For pagination, use the 'matchups' field.
  """
  halfDamageTo: [Type!]!

  """
  Convenience field for damage calculations. For pagination, use the 'matchups' field.
  """
  noDamageTo: [Type!]!
}

#
# CONNECTIONS AND EDGES
#

# ABILITY

type TypeBoostedByAbilityConnection implements Connection {
  edges: [TypeBoostedByAbilityEdge!]!
  pageInfo: PageInfo!
}

type TypeBoostedByAbilityEdge implements Edge {
  cursor: String!
  node: Type!
  multiplier: Float!
}

type TypeResistedByAbilityConnection implements Connection {
  edges: [TypeResistedByAbilityEdge!]!
  pageInfo: PageInfo!
}

type TypeResistedByAbilityEdge implements Edge {
  cursor: String!
  node: Type!
  multiplier: Float!
}

# GENERATION

type TypeGenerationConnection implements Connection {
  edges: [TypeGenerationEdge!]! 
  pageInfo: PageInfo!
}

type TypeGenerationEdge implements Edge {
  cursor: String!
  node: Generation!
}

# ITEM

type TypeNaturalGiftConnection implements Connection {
  edges: [TypeNaturalGiftEdge!]!
  pageInfo: PageInfo!
}

type TypeNaturalGiftEdge implements Edge {
  cursor: String!
  node: Item!

  """
  The power of Natural Gift when used by a Pokemon holding Item.
  """
  power: Int!
}

type TypeBoostedByItemConnection implements Connection {
  edges: [TypeBoostedByItemEdge!]!
  pageInfo: PageInfo!
}

type TypeBoostedByItemEdge implements Edge {
  cursor: String!
  node: Type!
  multiplier: Float!
}

type TypeResistedByItemConnection implements Connection {
  edges: [TypeResistedByItemEdge!]!
  pageInfo: PageInfo!
}

type TypeResistedByItemEdge implements Edge {
  cursor: String!
  node: Type!
  multiplier: Float!
}

# MOVE

type TypeMoveConnection implements Connection {
  edges: [TypeMoveEdge!]!
  pageInfo: PageInfo!
}

type TypeMoveEdge implements Edge {
  cursor: String!
  node: Move!
}

type TypeEnablesMoveConnection implements Connection {
  edges: [TypeEnablesMoveEdge!]!
  pageInfo: PageInfo!
}

type TypeEnablesMoveEdge implements Edge {
  cursor: String!
  node: Move!
}

# POKEMON

type TypePokemonConnection implements Connection {
  edges: [TypePokemonEdge!]!
  pageInfo: PageInfo!
}

type TypePokemonEdge implements Edge {
  cursor: String!
  node: Pokemon!
}

# TYPE

type TypeMatchupConnection implements Connection {
  edges: [TypeMatchupEdge!]!
  pageInfo: PageInfo!
}

type TypeMatchupEdge implements Edge {
  cursor: String!
  node: Type!

  """
  The multiplier of the Type-matchup, with the starting node as the attacking Type and the ending node as the defending Type.
  """
  multiplier: Float!
}