#
# QUERIES
#

extend type Query {
  usageMethodByID(id: ID!): UsageMethod!

  """
  Select a UsageMethod by its snake_case name, e.g. 'pulse'.
  """
  usageMethodByName(generation: Int = 8, name: String!): UsageMethod!
  
  """
  Select UsageMethods, with optional cursor-based pagination.

  'introducedAfter' and 'introducedBefore' refer to the number of a Generation, and are inclusive.

  'startsWith', 'contains', 'endsWith' refer to the name, and are case-insensitive.
  """
  usageMethods(
    generation: Int = 8
    pagination: PaginationInput
    filter: UsageMethodFilter
  ): [UsageMethod!]!
}

#
# NODES AND HELPER FIELDS
#

type UsageMethod implements Node {
  id: ID!

  boostedByAbility(filter: AbilityFilter): UsageMethodBoostedByAbilityConnection

  resistedByAbility(filter: AbilityFilter): UsageMethodResistedByAbilityConnection

  """
  The name of the UsageMethod in Title Case.
  """
  formattedName: String!

  """
  The Generation of this UsageMethod.
  """ 
  generation(filter: GenerationFilter): UsageMethodGenerationConnection
  
  """
  The Generation in which the UsageMethod became relevant. That is, in which the UsageMethod of the Move would interact with certain Abilities, Moves, etc. 
  
  For example, whether a Move had the UsageMethod 'bite' only became relevant when the ability 'strong_jaw' was introduced in Generation 6, even though Moves like 'crunch' have been around since Generation 2.
  """
  introduced(filter: GenerationFilter): UsageMethodIntroductionConnection

  boostedByItem(filter: ItemFilter): UsageMethodBoostedByItemConnection

  resistedByItem(filter: ItemFilter): UsageMethodResistedByItemConnection

  moves(filter: MoveFilter): UsageMethodMoveConnection

  """
  The name of the UsageMethod in snake_case. 
  """
  name: String!

}

#
# CONNECTIONS AND EDGES
#

# ABILITY

type UsageMethodBoostedByAbilityConnection implements Connection {
  count: Int!
  
  edges(
    pagination: PaginationInput
  ): [UsageMethodBoostedByAbilityEdge!]!

}

type UsageMethodBoostedByAbilityEdge implements Edge {  
  node: Ability!
  multiplier: Float!
}

type UsageMethodResistedByAbilityConnection implements Connection {
  count: Int!
  
  edges(
    pagination: PaginationInput
  ): [UsageMethodResistedByAbilityEdge!]!

}

type UsageMethodResistedByAbilityEdge implements Edge {  
  node: Ability!
  multiplier: Float!
}

# GENERATION

type UsageMethodGenerationConnection implements Connection {
  edges(
    pagination: PaginationInput
  ): [UsageMethodGenerationEdge!]! 

}

type UsageMethodGenerationEdge implements Edge {  
  node: Generation!
}

type UsageMethodIntroductionConnection implements Connection {
  edges(
    pagination: PaginationInput
  ): [UsageMethodIntroductionEdge!]! 

}

type UsageMethodIntroductionEdge implements Edge {  
  node: Generation!
}

# ITEM

type UsageMethodBoostedByItemConnection implements Connection {
  count: Int!
  
  edges(
    pagination: PaginationInput
  ): [UsageMethodBoostedByItemEdge!]!

}

type UsageMethodBoostedByItemEdge implements Edge {  
  node: Item!
  multiplier: Float!
}

type UsageMethodResistedByItemConnection implements Connection {
  count: Int!
  
  edges(
    pagination: PaginationInput
  ): [UsageMethodResistedByItemEdge!]!

}

type UsageMethodResistedByItemEdge implements Edge {  
  node: Item!
  multiplier: Float!
}

# MOVE

type UsageMethodMoveConnection implements Connection {
  count: Int!
  
  edges(
    pagination: PaginationInput
  ): [UsageMethodMoveEdge!]!

}

type UsageMethodMoveEdge implements Edge {  
  node: Move!
}

#
# INPUTS
#

input UsageMethodFilter {
  """
  The number of the Generation in which the UsageMethod was introduced.
  """
  introduced: Int

  """
  The number of the Generation after which the UsageMethod was introduced, inclusive.
  """
  introducedAfter: Int

  """
  The number of the Generation before which the UsageMethod was introduced, inclusive.
  """
  introducedBefore: Int

  """
  The name of the UsageMethod in snake_case.
  """
  name: String

  """
  Entities whose name contains the given string, case-insensitive.
  """
  contains: String

  """
  Entities whose name ends with the given string, case-insensitive.
  """
  endsWith: String

  """
  Entities whose name starts with the given string, case-insensitive.
  """
  startsWith: String
}