#
# NODES AND HELPER TYPES
#

type VersionGroup implements Node {
  id: ID!

  """
  The initials of the games in the VersionGroup, or an abbreviation. Corresponds with the conventions used on Bulbapedia.

  For example:
    'GS' for 'Gold/Silver'
    'C' for 'Crystal'
    'Pt' for 'Platinum'
    'Colo' for 'Colosseum'
    'PE' for 'Let's Go Pikachu and Eevee'
    'SwSh' for 'Sword/Shield'
  """
  code: String!

  descriptions(input: ConnectionInput): VersionGroupDescriptionConnection

  """
  The formatted name of the VersionGroup. If there are multiple games in the group, they are separated by a '/'.

  For example:
    'Gold/Silver' for 'GS'
    'SwSh' for 'Sword/Shield'
  """
  formattedName: String!

  """
  The Generation in which the VersionGroup was introduced. 
  """
  introduced(input: ConnectionInput): VersionGroupGenerationConnection

  sprites(input: ConnectionInput): VersionGroupSpriteConnection
}

#
# CONNECTIONS AND EDGES
# 

# DESCRIPTION

type VersionGroupDescriptionConnection implements Connection {
  edges: [VersionGroupDescriptionEdge!]! 
  pageInfo: PageInfo!
}

type VersionGroupDescriptionEdge implements Edge {
  cursor: String!
  node: Description!
}

# GENERATION

type VersionGroupGenerationConnection implements Connection {
  edges: [VersionGroupGenerationEdge!]! 
  pageInfo: PageInfo!
}

type VersionGroupGenerationEdge implements Edge {
  cursor: String!
  node: Generation!
}

# SPRITE

type VersionGroupSpriteConnection implements Connection {
  edges: [VersionGroupSpriteEdge!]! 
  pageInfo: PageInfo!
}

type VersionGroupSpriteEdge implements Edge {
  cursor: String!
  node: Sprite!
}